baseURL = 'https://notguigao-afk.github.io/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = 'PaperMod'

[params]
  # Landing hero (homepage only)
  [params.homeHero]
    eyebrow = ""
    title = "Live as if you were to die tomorrow."
    subtitle = "Learn as if you were to live forever."

  # 开启代码块复制按钮
  ShowCodeCopyButtons = true
